=== GeamXD/meta-stnd/schema/dc_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "title": {
        "description": "The name of the resource.",
        "type": "string"
      },
      "creator": {
        "description": "An entity primarily responsible for making the resource.",
        "type": "string"
      },
      "subject": {
        "description": "The topic of the resource.",
        "type": "string"
      },
      "description": {
        "description": "An account of the resource.",
        "type": "string"
      },
      "publisher": {
        "description": "An entity responsible for making the resource available.",
        "type": "string"
      },
      "contributor": {
        "description": "An entity responsible for making contributions to the resource.",
        "type": "string"
      },
      "date": {
        "description": "A point or period of time associated with an event in the lifecycle of the resource.",
        "type": "string",
        "format": "date-time"
      },
      "type": {
        "description": "The nature or genre of the resource.",
        "type": "string"
      },
      "format": {
        "description": "The file format, physical medium, or dimensions of the resource.",
        "type": "string"
      },
      "identifier": {
        "description": "An unambiguous reference to the resource within a given context.",
        "type": "string"
      },
      "source": {
        "description": "A related resource from which the described resource is derived.",
        "type": "string"
      },
      "language": {
        "description": "A language of the resource.",
        "type": "string"
      },
      "relation": {
        "description": "A related resource.",
        "type": "string"
      },
      "coverage": {
        "description": "The spatial or temporal topic of the resource.",
        "type": "string"
      },
      "rights": {
        "description": "Information about rights held in and over the resource.",
        "type": "string"
      }
    },
    "required": [
      "title",
      "creator",
      "subject",
      "description",
      "publisher"
    ]
  }

=== GeamXD/meta-stnd/sample/valid/dc_valid.json
{
    "title": "Metadata Example",
    "creator": "John Doe",
    "subject": "Metadata Example sub",
    "description": "This is an example of a Dublin Core metadata record.",
    "publisher": "OpenAI",
    "contributor": "Jane Smith",
    "date": "2024-08-10",
    "type": "Text",
    "format": "text/xml",
    "identifier": "https://www.example.com/sample-metadata",
    "source": "Original Source",
    "language": "en",
    "relation": "IsPartOf Example Collection",
    "coverage": "Global",
    "rights": "Public Domain"
  }
